{
  parserClass="me.khol.intellij.plugin.language.parser.LowlightingParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Lowlighting"
  psiImplClassSuffix="Impl"
  psiPackage="me.khol.intellij.plugin.language.psi"
  psiImplPackage="me.khol.intellij.plugin.language.psi.impl"

  elementTypeHolderClass="me.khol.intellij.plugin.language.psi.LowlightingTypes"
  elementTypeClass="me.khol.intellij.plugin.language.psi.LowlightingElementType"
  tokenTypeClass="me.khol.intellij.plugin.language.psi.LowlightingTokenType"

  psiImplUtilClass="me.khol.intellij.plugin.language.psi.impl.LowlightingPsiImplUtil"
}

lowlightingFile ::= item_*

private item_ ::= (property|COMMENT|CRLF)

property ::= KEY {
  mixin="me.khol.intellij.plugin.language.psi.impl.LowlightingNamedElementImpl"
  implements="me.khol.intellij.plugin.language.psi.LowlightingNamedElement"
  methods=[getName setName getNameIdentifier]
}
